FROM openshift/origin-release:golang-1.15 as builder

WORKDIR /go/src/github.com/open-cluster-management/provider-credential-controller
COPY . .

RUN make -f Makefile.prow compile

FROM registry.access.redhat.com/ubi8/ubi-minimal:latest

ENV USER_UID=1001

# Add the binaries
COPY --from=builder /go/src/github.com/open-cluster-management/provider-credential-controller/build/_output/manager .

USER ${USER_UID}