FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_8_1.22 AS builder

WORKDIR /go/src/github.com/stolostron/provider-credential-controller
COPY . .

RUN make -f Makefile.prow compile

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

ENV USER_UID=1001

# Add the binaries
COPY --from=builder /go/src/github.com/stolostron/provider-credential-controller/build/_output/manager .
COPY --from=builder /go/src/github.com/stolostron/provider-credential-controller/build/_output/old-provider-connection .

USER ${USER_UID}
